newline_style = "unix"
use_field_init_shorthand = true
unstable_features = true
version = "Two"
comment_width = 100
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
wrap_comments = true
